import torch.nn as nn

class Generator(nn.Module):
    def __init__(self, input_res: int):
        super(Generator, self).__init__()
        self.input_res = input_res
        print(f'input_res: {input_res}')
        self.upsample1 = nn.Upsample(scale_factor=2, mode='nearest')
        self.conv1 = nn.Conv2d(in_channels=input_res ** 2, out_channels=(input_res // 2) ** 2, kernel_size=3, stride=1, padding=1)
        self.upsample2 = nn.Upsample(scale_factor=2, mode='nearest')
        self.conv2 = nn.Conv2d(in_channels=(input_res // 2) ** 2, out_channels=(input_res // 4) ** 2, kernel_size=3, stride=1, padding=1)
        self.upsample3 = nn.Upsample(scale_factor=2, mode='nearest')
        self.conv3 = nn.Conv2d(in_channels=(input_res // 4) ** 2, out_channels=(input_res // 8) ** 2, kernel_size=3, stride=1, padding=1)
        self.upsample4 = nn.Upsample(scale_factor=2, mode='nearest')
        self.conv4 = nn.Conv2d(in_channels=(input_res // 8) ** 2, out_channels=(input_res // 16) ** 2, kernel_size=3, stride=1, padding=1)
        self.upsample5 = nn.Upsample(scale_factor=2, mode='nearest')
        self.conv5 = nn.Conv2d(in_channels=(input_res // 16) ** 2, out_channels=(input_res // 32) ** 2, kernel_size=3, stride=1, padding=1)
        self.upsample6 = nn.Upsample(scale_factor=2, mode='nearest')
        self.conv6 = nn.Conv2d(in_channels=(input_res // 32) ** 2, out_channels=(input_res // 64) ** 2, kernel_size=3, stride=1, padding=1)
        self.activation = nn.Sigmoid()
        
    def forward(self, x):
        # print(f'raw x: {x.shape}')
        x = x.view(x.size(0), self.input_res * self.input_res, 1, 1)  # Reshape input to (batch_size, 4096, 1, 1)
        # print(f'reshaped x: {x.shape}')
        x = self.upsample1(x)
        # print(f'upsampled x: {x.shape}')
        x = self.activation(self.conv1(x))
        # print(f'conv1 x: {x.shape}')
        x = self.upsample2(x)
        # print(f'upsampled x: {x.shape}')
        x = self.activation(self.conv2(x))
        # print(f'conv2 x: {x.shape}')
        x = self.upsample3(x)
        # print(f'upsampled x: {x.shape}')
        x = self.activation(self.conv3(x))
        # print(f'conv3 x: {x.shape}')
        x = self.upsample4(x)
        # print(f'upsampled x: {x.shape}')
        x = self.activation(self.conv4(x))
        # print(f'conv4 x: {x.shape}')
        x = self.upsample5(x)
        # print(f'upsampled x: {x.shape}')
        x = self.activation(self.conv5(x))
        # print(f'conv5 x: {x.shape}')
        x = self.upsample6(x)
        # print(f'upsampled x: {x.shape}')
        x = self.activation(self.conv6(x))
        # print(f'conv6 x: {x.shape}')
        return x